%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming
%% Source: /net/isildur/ldisk/daily_build/19_prebuild_master-opu_o.2016-06-21_20/otp_src_19/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.4.1
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_HRL).
-define(COSNAMING_HRL, true).


-record('CosNaming_NameComponent', {id, kind}).
-record('CosNaming_Binding', {binding_name, binding_type}).


-endif.


