%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m
%% Source: /net/isildur/ldisk/daily_build/19_prebuild_master-opu_o.2016-06-21_20/otp_src_19/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.4.1
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_HRL).
-define(M_HRL, true).


-record(m_NotAnInteger, {'OE_ID'="IDL:m/NotAnInteger:1.0"}).


-endif.


