#!/bin/bash

BASH=bash-4.3.30

source .tools

cd tmp
cp -r $XILLI/src/$BASH .
cd $BASH

./configure \
	--prefix=/tools \
	--without-bash-malloc \
	--enable-static-link \
	--disable-nls
	
sed -i s%\-rdynamic%% Makefile
sed -i s%\-rdynamic%% builtins/Makefile
make
make install
