#!/bin/bash


BINUTILS=binutils-2.27

cd tmp
rm -rf $BINUTILS
cp -R $XILLI/src/$BINUTILS .
mkdir $BINUTILS
cd $BINUTILS
mkdir build
cd build
export CC=/tools/bin/musl-gcc -Wl,-Bstatic -static-libgcc
export CXX=/tools/bin/musl-gcc -Wl,-Bstatic -static-libgcc
../configure \
	--prefix=/tools \
	--with-sysroot=/tools \
	--with-lib-path=/tools/lib \
	--target=x86_64-linux-musl \
	--disable-shared \
	--enable-static

make -j`nproc`
make install
