#!/tools/bin/bash

PERLSRC=perl-5.24.0

source .tools

cd tmp
rm -rf $PERLSRC
cp -R $XILLI/src/$PERLSRC .
cd $PERLSRC

/tools/bin/bash Configure -des -Dprefix=/tools -Dlibs=-lm -Dcc="$CC" -Dcxx="$CXX" -Dld="$LD" -Dar="$AR" -Dranlib="$RANLIB" -Dccdlflags="-static"

# cp $XILLI/patches/perl/Makefile .

make
make install
