#!/tools/bin/bash

. .tools

cd tmp
rm -rf sbase
cp -r $XILLI/src/sbase .
cd sbase

cat >config.mk <<CONFIGMK
# sbase version
VERSION = 0.0

# paths
PREFIX = /tools
MANPREFIX = /tools/share/man

CC = $CC
AR = $AR
RANLIB = $RANLIB

# for NetBSD add -D_NETBSD_SOURCE
# -lrt might be needed on some systems
CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_FILE_OFFSET_BITS=64
CFLAGS   = -std=c99 -Wall -pedantic
LDFLAGS  = -s

CONFIGMK

make
make install
