%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_FilterNotFound
%% Source: /net/isildur/ldisk/daily_build/19_prebuild_master-opu_o.2016-06-21_20/otp_src_19/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.4.1
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_FilterNotFound').
-ic_compiled("4_4_1").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0",
                   "FilterNotFound",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/FilterNotFound:1.0".

%% returns name
name() -> "CosNotifyFilter_FilterNotFound".



