%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_AlreadyConnected
%% Source: /net/isildur/ldisk/daily_build/19_prebuild_master-opu_o.2016-06-21_20/otp_src_19/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.1
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_AlreadyConnected').
-ic_compiled("4_4_1").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0",
                   "AlreadyConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0".

%% returns name
name() -> "CosEventChannelAdmin_AlreadyConnected".



