%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_PropertyTypes
%% Source: /net/isildur/ldisk/daily_build/19_prebuild_master-opu_o.2016-06-21_20/otp_src_19/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.1
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_PropertyTypes').
-ic_compiled("4_4_1").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_TypeCode,0}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/PropertyTypes:1.0".

%% returns name
name() -> "CosPropertyService_PropertyTypes".



