%%% This file was automatically generated by snmpc_mib_to_hrl version 5.2.3
%%% Date: 21-Jun-2016::21:09:15
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
