#!/bin/bash

PKGCONFIG=pkg-config-0.29.1

rm -rf /tmp/$PKGCONFIG
cp -R /src/$PKGCONFIG /tmp
cd /tmp/$PKGCONFIG

autoreconf -f -i

pushd /tmp/pkg-config-0.29.1/glib
autoreconf -f -i
popd

./configure --prefix=/ --disable-shared --enable-static --with-internal-glib

patch -p2 <<PATCH
--- src/pkg-config-0.29.1/glib/glib/gdate.c     2016-09-24 04:04:11.246610128 +0000
+++ tmp/pkg-config-0.29.1/glib/glib/gdate.c     2016-09-26 15:02:05.174665467 +0000
@@ -2486,33 +2486,6 @@
     }
 
   tmpbufsize = MAX (128, locale_format_len * 2);
-  while (TRUE)
-    {
-      tmpbuf = g_malloc (tmpbufsize);
-
-      /* Set the first byte to something other than '\0', to be able to
-       * recognize whether strftime actually failed or just returned "".
-       */
-      tmpbuf[0] = '\1';
-      tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
-
-      if (tmplen == 0 && tmpbuf[0] != '\0')
-        {
-          g_free (tmpbuf);
-          tmpbufsize *= 2;
-
-          if (tmpbufsize > 65536)
-            {
-              g_warning (G_STRLOC "Maximum buffer size for g_date_strftime exceeded: giving up\n");
-              g_free (locale_format);
-
-              s[0] = '\0';
-              return 0;
-            }
-        }
-      else
-        break;
-    }
   g_free (locale_format);
 
   convbuf = g_locale_to_utf8 (tmpbuf, tmplen, NULL, &convlen, &error);
PATCH

make
make install
